# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'playerGUI.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(813, 1045)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label = QtGui.QLabel(self.frame)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_2.addWidget(self.label)
        self.librTree = QtGui.QTreeView(self.frame)
        self.librTree.setObjectName(_fromUtf8("librTree"))
        self.verticalLayout_2.addWidget(self.librTree)
        self.horizontalLayout.addWidget(self.frame)
        self.frame_2 = QtGui.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.groupBox_2 = QtGui.QGroupBox(self.frame_2)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.quView = QtGui.QListView(self.groupBox_2)
        self.quView.setObjectName(_fromUtf8("quView"))
        self.verticalLayout_4.addWidget(self.quView)
        self.queryQu = QtGui.QPushButton(self.groupBox_2)
        self.queryQu.setObjectName(_fromUtf8("queryQu"))
        self.verticalLayout_4.addWidget(self.queryQu)
        self.clearQu = QtGui.QPushButton(self.groupBox_2)
        self.clearQu.setObjectName(_fromUtf8("clearQu"))
        self.verticalLayout_4.addWidget(self.clearQu)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.frame_3 = QtGui.QFrame(self.frame_2)
        self.frame_3.setMaximumSize(QtCore.QSize(999, 169))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.verticalLayout = QtGui.QVBoxLayout(self.frame_3)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.songLabel = QtGui.QLabel(self.frame_3)
        self.songLabel.setObjectName(_fromUtf8("songLabel"))
        self.verticalLayout.addWidget(self.songLabel)
        self.artistLabel = QtGui.QLabel(self.frame_3)
        self.artistLabel.setObjectName(_fromUtf8("artistLabel"))
        self.verticalLayout.addWidget(self.artistLabel)
        self.albumLabel = QtGui.QLabel(self.frame_3)
        self.albumLabel.setObjectName(_fromUtf8("albumLabel"))
        self.verticalLayout.addWidget(self.albumLabel)
        self.genreLabel = QtGui.QLabel(self.frame_3)
        self.genreLabel.setMinimumSize(QtCore.QSize(233, 21))
        self.genreLabel.setObjectName(_fromUtf8("genreLabel"))
        self.verticalLayout.addWidget(self.genreLabel)
        self.themeLabel = QtGui.QLabel(self.frame_3)
        self.themeLabel.setObjectName(_fromUtf8("themeLabel"))
        self.verticalLayout.addWidget(self.themeLabel)
        self.verticalLayout_3.addWidget(self.frame_3)
        self.frame_4 = QtGui.QFrame(self.frame_2)
        self.frame_4.setMaximumSize(QtCore.QSize(317, 105))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.gridLayout = QtGui.QGridLayout(self.frame_4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.Play = QtGui.QPushButton(self.frame_4)
        self.Play.setObjectName(_fromUtf8("Play"))
        self.gridLayout.addWidget(self.Play, 0, 1, 1, 1)
        self.Next_2 = QtGui.QPushButton(self.frame_4)
        self.Next_2.setObjectName(_fromUtf8("Next_2"))
        self.gridLayout.addWidget(self.Next_2, 0, 2, 1, 1)
        self.Prev = QtGui.QPushButton(self.frame_4)
        self.Prev.setObjectName(_fromUtf8("Prev"))
        self.gridLayout.addWidget(self.Prev, 0, 0, 1, 1)
        self.changeTheme = QtGui.QPushButton(self.frame_4)
        self.changeTheme.setMinimumSize(QtCore.QSize(0, 0))
        self.changeTheme.setMaximumSize(QtCore.QSize(189, 32))
        self.changeTheme.setObjectName(_fromUtf8("changeTheme"))
        self.gridLayout.addWidget(self.changeTheme, 1, 0, 1, 1)
        self.Pause = QtGui.QPushButton(self.frame_4)
        self.Pause.setObjectName(_fromUtf8("Pause"))
        self.gridLayout.addWidget(self.Pause, 1, 2, 1, 1)
        self.verticalLayout_3.addWidget(self.frame_4)
        self.horizontalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 813, 31))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuMusic = QtGui.QMenu(self.menubar)
        self.menuMusic.setObjectName(_fromUtf8("menuMusic"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionAdd_Song = QtGui.QAction(MainWindow)
        self.actionAdd_Song.setObjectName(_fromUtf8("actionAdd_Song"))
        self.actionAddPlaylist = QtGui.QAction(MainWindow)
        self.actionAddPlaylist.setObjectName(_fromUtf8("actionAddPlaylist"))
        self.actionUpdate = QtGui.QAction(MainWindow)
        self.actionUpdate.setObjectName(_fromUtf8("actionUpdate"))
        self.menuMusic.addAction(self.actionAdd_Song)
        self.menuMusic.addAction(self.actionAddPlaylist)
        self.menuMusic.addAction(self.actionUpdate)
        self.menubar.addAction(self.menuMusic.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label.setText(_translate("MainWindow", "Library:", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Queue", None))
        self.queryQu.setText(_translate("MainWindow", "Query to Queue", None))
        self.clearQu.setText(_translate("MainWindow", "Clear Queue", None))
        self.songLabel.setText(_translate("MainWindow", "Song:", None))
        self.artistLabel.setText(_translate("MainWindow", "Artist:", None))
        self.albumLabel.setText(_translate("MainWindow", "Album:", None))
        self.genreLabel.setText(_translate("MainWindow", "Genre:", None))
        self.themeLabel.setText(_translate("MainWindow", "Theme:", None))
        self.Play.setText(_translate("MainWindow", "Play", None))
        self.Next_2.setText(_translate("MainWindow", "-->", None))
        self.Prev.setText(_translate("MainWindow", "<--", None))
        self.changeTheme.setText(_translate("MainWindow", "Theme", None))
        self.Pause.setText(_translate("MainWindow", "Pause", None))
        self.menuMusic.setTitle(_translate("MainWindow", "Music", None))
        self.actionAdd_Song.setText(_translate("MainWindow", "Add Song", None))
        self.actionAddPlaylist.setText(_translate("MainWindow", "Add Album/Playlist", None))
        self.actionUpdate.setText(_translate("MainWindow", "Update Library", None))

